### ISSUE TITLE
Introduce alternative converter parameter in conversion method

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-ruby#10]
Some formats have several converters, for example, docx to pdf has three of them listed below.
It should be a possibility to set up an alternative converter from the library in the Convert method.

https://v2.convertapi.com/convert/docx/to/pdf
https://v2.convertapi.com/convert/docx/to/pdf/converter/openoffice
https://v2.convertapi.com/convert/docx/to/pdf/converter/printer

This is only an example of a convert method on how it could implement alternative converters.

Default method

ConvertApi.convert('pdf', File: '/path/to/my_file.docx')

with alternative converter

ConvertApi.convert('pdf', File: '/path/to/my_file.docx', converter:  'openoffice')

**Comment by laurynas-baltsoft** [comment]
Already implemented by @jonas-jasas in `v1.2.0`: https://github.com/ConvertAPI/convertapi-ruby/commit/c0acbebf78e8594c0f8f140614cbe55f5f5b6ac7
