### ISSUE TITLE
Documentation improvement 

### ISSUE THREAD

**Issue by JonasJasas** [ConvertAPI/convertapi-ruby#11]
A comment from the user:
> It would be really helpful if you provided better documentation on how to access elements of the response objects your API returns. It took me forever to figure out how to actually get the files that  were converted, and I did it on my own, not with your documentation. For example, it was not  obvious that the response object was returning an array of files that I could access like this:
```
rtf_file = ConvertApi.convert('rtf', File: 'new.pdf')

rtf_url = rtf_file.files[0].url
open('rtf_file.rtf', 'wb') do |file|
file << open(rtf_url).read
end
```

**Comment by laurynas-baltsoft** [comment]
Updated README: 
https://github.com/ConvertAPI/convertapi-ruby#accessing-result-files
