### ISSUE TITLE
Gem incompatible with ruby-2.7.0 and upwards

### ISSUE THREAD

**Issue by ghousemohamed** [ConvertAPI/convertapi-ruby#15]
Previously, in one of the project, I had been using this gem with ruby-2.6.5. After upgrading the ruby version to 2.7.2 I started getting some errors. Specifically when I tried to save the converted file using the `save` method on the `ConvertApi::ResultFile` module.

when I try to save the converted file like so: `converted.file.save('/path/to/file')`

I'm getting this error: `ArgumentError (extra arguments)`

**Comment by laurynas-baltsoft** [comment]
Hi @ghousemohamed, I have tested with ruby 2.7.2 and this example works fine for me:

```ruby
result = ConvertApi.convert(
  'pdf',
  {
    Url: 'https://en.wikipedia.org/wiki/Data_conversion',
    FileName: 'web-example'
  },
  from_format: 'web',
  conversion_timeout: 180,
)

p result.file.save('/tmp/test.pdf')
```

Could you please try if it works for you and if not - please provide error stack trace.

**Comment by laurynas-baltsoft** [comment]
Also please make sure you are using latest gem version `1.3.0`.

**Comment by ghousemohamed** [comment]
`result = ConvertApi.convert('jpg', { File: "tmp/template.html", ImageQuality: 100, ImageWidth: 500, ImageHeight: 500}, from_format: 'html')`

**Comment by tomasr78** [comment]
@laurynas-baltsoft Can we close it?

**Comment by laurynas-baltsoft** [comment]
Yes, I think we can.
