### ISSUE TITLE
ConvertApi::ConnectionFailed end of file reached

### ISSUE THREAD

**Issue by vasilis-GenHome** [ConvertAPI/convertapi-ruby#17]
We are experiencing an issue while trying to convert and merge a pdf.

The error we get is
ConvertApi::ConnectionFailed end of file reached

AFAIK, we haven't touched our side of the code.

Do you have any idea what the source of this problem might be?
I went through the docs and couldn't find anything.

Also our dashboard shows 0 failures and your status page shows that everything is operational.

**Comment by tomasr78** [comment]
I have no idea why you get this problem. Do you still have the issue?

**Comment by vasilis-GenHome** [comment]
Thank you for coming back @tomasr78 
Turns out there was a problem with the internet connection at the office which we guess is the root cause.
Thank you for your quick reply!!
