### ISSUE TITLE
ConvertApiUser.SecondsLeft property is depreciated

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-ruby#26]
https://github.com/ConvertAPI/convertapi-dotnet/issues/50

**Comment by tomasr78** [comment]
@tomasr78 Can you fix and remove?

**Comment by laurynas-convertapi** [comment]
It was used in readme only. Updated: https://github.com/ConvertAPI/convertapi-ruby/commit/12574a317f126e6727aacd63bf36db1087df2b3b
