### ISSUE TITLE
Incorrect parameter name in URL example

### ISSUE THREAD

**Issue by samstickland** [ConvertAPI/convertapi-ruby#8]
In this example the parameter name is `Url`, but actually this generates a blank PDF (presumably there is some error that isn't reported)

https://github.com/ConvertAPI/convertapi-ruby/blob/1117620b589505aa8932aa7c1a6a60a697cf3573/examples/convert_url_to_pdf.rb#L14

Using `File` as the parameter works correctly, which is odd as this contradicts the API documentation, but matches the CLI command.

**Comment by laurynas-baltsoft** [comment]
Hi @samstickland, I have tested the example and conversion worked fine for me - PDF file was created with the page content. Are you still experiencing the this problem?

I have executed example like this:
`CONVERT_API_SECRET=replacewithsecret ruby ./examples/convert_url_to_pdf.rb`

If you are still getting blank PDF, could you please specify what kind of OS and ruby version you use to run the example.
